# This is a basic workflow to help you get started with Actions

name: Automation Example

on:
  issues:
    types: [opened]
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Hello Welcome To Devtools Organizarion",
              description: "The entire team of Devtools is thrilled to welcome you on board. We hope you'll do some amazing works here! A warm welcome and lots of good wishes on becoming part of our growing team."
         
            })

